### ISSUE TITLE
Examples of outlying RVs 

### ISSUE THREAD

**Issue by Emmavt** [Keck-DataReductionPipelines/KPF-Pipeline#961]
Following up on meeting with Andrew and Howard yesterday, here are the observation IDs for several outlying RVs in my 2024A+B programs observing M dwarf multis. Several of them have WLS files that are separated by 2-4 days, which is likely the issue.

- TIC415969908 (TOI 233)
	- KP.20240615.48817.18
- TIC318022259 (TOI 1730)
	- KP.20240226.39775.54 
	- KP.20240424.27690.19 
- TOI-2274 (TOI 2274)
	- KP.20240226.52888.33 
	- KP.20240227.52250.54 
- TIC198162530 (TOI 5738)
	- KP.20240914.21049.56

**Comment by awhoward** [comment]
Thank you for this, @Emmavt !

@howardisaacson, @bjfultn, @shalverson, @lukehandley -- let's try to categorize these outlier RVs and make sure that we're working toward solutions for all of them.

**Comment by awhoward** [comment]
I would welcome examples of other outlier RVs from other users to be posted to this thread.

**Comment by lukehandley** [comment]
Here's an example of 3 consecutive exposures of the same target (201092) which seem to have identical WLS attributes, but one of the three has ~km/s difference from the others, as well as double the SNR:

KP.20240526.53616.48
KP.20240526.53725.34
KP.20240526.53833.94 (Outlier)

**Comment by bjfultn** [comment]
KP.20240526.53833.94 has different TARG header keywords.

**Comment by bpholden** [comment]
Looking through the history database, the radial velocity keyword was
zeroed out during the last exposure, 30 seconds before the end.

That should not matter, the values used are supposed to be those at the
start of the exposure, allowing the observer to reset the values before
read out begins.
It could be that the window for the beginning is too larger, I will ask.

Brad

**Comment by lukehandley** [comment]
Looking at the keywords from the L2 files, the outlier observation was processed as DCSNAME = 201091, i.e. the binary companion.

Based on the observing notes, there was an interruption during observing these targets on that night which required restarting the sequence. Perhaps an observer incorrectly edited the OB?

**Comment by CJRogers01** [comment]
The outliers that I've encountered for my set of TESS follow-up targets:

TOI-1184:
- KP.20240226.52167.15 (off by ~140 m/s from the other observations of this target)

TOI-5726:
- KP.20240225.47797.38 (off by ~260 m/s from the other observations of this target, but this exposure had the simulcal turned on and the spectrum flux is quite low compared to the simulcal in this exposure)
- KP.20240226.41695.77 (off by ~160 m/s from the other observations, no obvious cause that I've found)
- KP.20240227.42617.29 (off by ~60 m/s from the other observations, no obvious cause that I've found)

**Comment by bjfultn** [comment]
Howard and I went through and added comments about each of the observations listed here so far.

In all cases we are either missing bracketing LFC calibrations and we need to wait until we implement an etalon-based drift correction, or the TARG header keywords set at the telescope from the OB are inconsistent.

**Comment by aspolanski** [comment]
From Stephen Kane and I's 30 target program, I've attached another tranche of outliers I've found
[nov2024_outliers.txt](https://github.com/user-attachments/files/17824391/nov2024_outliers.txt)

Particularly common problem dates appear to be anything taken between [2-24-2024,2-27-2024], [6-17-2024,6-18-2024], 9-8-2024, and 9-1-2024

**Comment by CJRogers01** [comment]
Ran into a new outlier : when I looked at the data for TOI-5726 back in October, this exposure was fine, but now (reprocessed with the new pipeline) it's off from everything else by ~15 km/s.
Observation ID **KP.20240402.39973.62**. From looking at the intermediate data products, the green CCF seems to be working fine, but the red CCF is not grabbing the absorption lines at all. No apparent reason why; it looks like there's WLS files from that day, and the flux is fine on the red CCF.

**Comment by howardisaacson** [comment]
@clairejrogers We are now running a reprocessing moving backwards in time from present, currently on ~1 Feb 2025.  The Oct 2024 data was run as a test set, so until everything that you are looking at is run on the same DRP version, there may be inconsistencies.

**Comment by awhoward** [comment]
@clairejrogers, how does it look for TOI-5726 now?

**Comment by awhoward** [comment]
@Emmavt -- could you check out the quality of the observations that you mentioned above?  See also my note above about reprocessing.

**Comment by clairejrogers** [comment]
@awhoward TOI-5726 looks good now! The outlier that showed up with 2.8.2 and the three outliers noted in November are all in the same range as the other RVs since reprocessing.

**Comment by Emmavt** [comment]
I took at look at several targets under the KSMS program (Program ID N052). Post-reprocessing, all but one of the outliers have been resolved. The remaining outlier is:
- TOI-1630: KP.20241019.42853.32.

Regarding the targets I mentioned in my original comment, under programs U277 and U288, 
- TOI-1730: KP.20240424.27690.19 is still outlying
- TOI-2274: KP.20240226.52888.33 is still outlying, and flagged as a junk observation though recoverable by BJ
- TOI-5738: KP.20250207.56340.68 might be a new outlier in this data set

**Comment by maxkroft** [comment]
Some outliers with TOI-1716 on the new DRP:
- KP.20250209.23611.77 is about 150 m/s off
- KP.20250429.22054.14 and KP.20250505.22798.33, which were taken after the most recent servicing mission, are about 40 m/s off from each other. I would expect to need to fit a new offset to the new data, however it is strange that these two are so far off of each other. The first point is consistent with pre-servicing data, while the second point is not.

**Comment by pranavp25** [comment]
Hi all,

I found a small outlier in one of our targets, TOI 2211, off by ~15 m/s
Obs ID - KP.20240715.48951.68

As a note, there seems to be a single order in the Red CCD thats messing things, which is seen in another observation we have from that night for a different target (HD 189733). This issue persisted from DRP 2.8.2 when I first saw this

**Comment by howardisaacson** [comment]
@pranavp25 We have implemented a bad pixel mask that 'should' take care of this in the next reprocessing. 
Obs; For KP.20240715.48951.68.

**Comment by awhoward** [comment]
@howardisaacson, @lukehandley, @bjfultn, all -- let's reassess the outliers noted above with the reprocessing that started this week.
